apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.secretstore
  namespace: reddog-branch
spec:
  type: secretstores.azure.keyvault
  metadata:
    - name: vaultName
      value: reddog-branch
    - name: spnClientId
      value: 
    - name: spnTenantId
      value: 
    - name: spnCertificate
      secretKeyRef:
        name: reddog.secretstore
        key: secretstore-cert
