apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: reddog.config
  namespace: reddog-branch
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://localhost:9411/api/v2/spans
