apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.state.makeline
  namespace: reddog-branch
spec:
  type: state.redis
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""
scopes:
  - make-line-service
