apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-worker
  namespace: reddog-branch
  labels:
    app: virtual-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-worker
  template:
    metadata:
      labels:
        app: virtual-worker
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "virtual-worker"
        dapr.io/app-port: "80"
        dapr.io/config: "reddog.config"
    spec:
      containers:
        - name: virtual-worker
          image: "ghcr.io/cloudnativegbb/paas-vnext/reddog-virtual-worker:latest"
          imagePullPolicy: Always
          env:
          - name: STORE_ID
            value: Denver
          - name: MIN_SECONDS_TO_COMPLETE_ITEM
            value: 2
          - name: MAX_SECONDS_TO_COMPLETE_ITEM
            value: 12