data:
  FUNCTIONS_WORKER_RUNTIME: bm9kZQ==
  rabbitMQConnectionAppSetting: YW1xcDovL3JlZGRvZzpCcm9ueDEwNDY1WThkcHdteHFAMjAuODQuMjUuNTY6NTY3Mg==
  AzureWebJobsStorage: VXNlRGV2ZWxvcG1lbnRTdG9yYWdlPXRydWU=
  MyServiceBusConnection: RW5kcG9pbnQ9c2I6Ly9icmlhcnJlZGRvZ2RlbW8uc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1Sb290TWFuYWdlU2hhcmVkQWNjZXNzS2V5O1NoYXJlZEFjY2Vzc0tleT1YVGlsRG1TMDRnYytJYkFWTG56Q1FSeU5YU1puSmw4WXNIYWJaWFZRM0NJPQ==
apiVersion: v1
kind: Secret
metadata:
  name: corp-transfer-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: corp-transfer-service
  labels:
    app: corp-transfer-service
spec:
  selector:
    matchLabels:
      app: corp-transfer-service
  template:
    metadata:
      labels:
        app: corp-transfer-service
    spec:
      containers:
      - name: corp-transfer-service
        image: ghcr.io/cloudnativegbb/paas-vnext/corp-transfer-service:latest
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: RabbitQueueTrigger
        envFrom:
        - secretRef:
            name: corp-transfer-service
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: corp-transfer-service
  labels: {}
spec:
  scaleTargetRef:
    name: corp-transfer-service
  pollingInterval: 20
  cooldownPeriod: 300
  triggers:
  - type: rabbitmq
    metadata:
      direction: in
      queueName: corp-transfer-orders
      hostFromEnv: rabbitMQConnectionAppSetting
---

